# seasalt bash integration (generated by `seasalt init bash`)
if command -v "${SEASALT_BIN:-seasalt}" >/dev/null 2>&1 || [[ -n ${SEASALT_BIN:-} ]]; then
  _seasalt_bin=${SEASALT_BIN:-seasalt}

  _seasalt_session="$$-$RANDOM-$RANDOM"
  _seasalt_last_id=

  function _seasalt_preexec {
    local cmd=${1:-}
    [[ $cmd ]] || return 0
    _seasalt_last_id=$("$_seasalt_bin" record --cwd "$PWD" --session "$_seasalt_session" -- "$cmd" 2>/dev/null)
    case $_seasalt_last_id in
      (''|*[!0-9]*) _seasalt_last_id= ;;
    esac
  }

  function _seasalt_precmd {
    local code=$?
    if [[ $_seasalt_last_id ]]; then
      "$_seasalt_bin" exit --session "$_seasalt_session" --last-id "$_seasalt_last_id" --code "$code" >/dev/null 2>&1
      _seasalt_last_id=
    fi
  }

  if declare -F blehook >/dev/null 2>&1; then
    blehook PREEXEC+=_seasalt_preexec
    blehook PRECMD+=_seasalt_precmd

    if (( ${#_ble_complete_auto_source[@]} )); then
      case " ${_ble_complete_auto_source[*]} " in
        (*" seasalt "*) ;;
        (*) _ble_complete_auto_source=(seasalt "${_ble_complete_auto_source[@]}") ;;
      esac
    else
      _ble_complete_auto_source=(seasalt history syntax)
    fi

    function ble/complete/auto-complete/source:seasalt {
      [[ ${_ble_edit_str:-} ]] || return 1
      ((_ble_edit_ind == ${#_ble_edit_str})) || return 1
      local cmd suggest
      cmd=$(timeout 0.2 "$_seasalt_bin" suggest --cwd "$PWD" -- "$_ble_edit_str" 2>/dev/null) || return 1
      [[ $cmd ]] || return 1
      [[ $cmd == "$_ble_edit_str" ]] && return 1
      suggest=${cmd:${#_ble_edit_str}}
      ble/complete/auto-complete/enter h 0 "$suggest" '' "$cmd"
    }
  fi
fi
